### ISSUE TITLE
Create initial requirements

### ISSUE THREAD

**Issue by mdhenney** [first-team-58/2020-InfiniteRecharge#1]
Need initial requirements and design documented for the robot software.

## Tasks
- [ ] Document initial [requirements](https://github.com/first-team-58/2020-InfiniteRecharge/wiki/Requirements) for the software to support robot prototypes
- [ ] Document high-level software [design](https://github.com/first-team-58/2020-InfiniteRecharge/wiki/Design)
- [ ] Document initial robot design
